### ISSUE TITLE
java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)

### ISSUE THREAD

**Issue by ronykrell** [sephiroth74/NumberSlidingPicker#11]
Error occurs when loading number picker inside a viewholder in a recycler view
XML Config:

```
<it.sephiroth.android.library.numberpicker.NumberPicker
        style="@style/NumberPicker.Filled"
        android:id="@+id/item_assign_box_assigned"
        android:layout_width="0dp"
        app:picker_disableGestures="true"
        android:layout_height="wrap_content"
        android:layout_weight="1.5"
        android:layout_marginEnd="8dp"
        app:picker_orientation="vertical"
        app:picker_tracker="exponential"
        tools:text="123" />
```

Code:
 ```
        holder.numberAssigned.setMinValue(0);
        holder.numberAssigned.setMaxValue(inside.getQuantity()-inside.getQuantityAssigned());
        holder.numberAssigned.setStepSize(1);
        holder.numberAssigned.setProgress(0);
```
Stack Trace
```
W/System.err: java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:487)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
        at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
        at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
        at org.jacoco.agent.rt.internal_8ff85ea.Offline.getProbes(Offline.java:51)
        at it.sephiroth.android.library.uigestures.UIGestureRecognizerDelegate.$jacocoInit(UIGestureRecognizerDelegate.kt)
        at it.sephiroth.android.library.uigestures.UIGestureRecognizerDelegate.<init>(UIGestureRecognizerDelegate.kt)
        at it.sephiroth.android.library.numberpicker.NumberPicker.<init>(NumberPicker.kt:61)
        at it.sephiroth.android.library.numberpicker.NumberPicker.<init>(NumberPicker.kt:42)
        at it.sephiroth.android.library.numberpicker.NumberPicker.<init>(NumberPicker.kt)
        at java.lang.reflect.Constructor.newInstance(Native Method)
W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:619)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at com.plantecuador.poscosecha.adapter.AssignAdapterChooseBoxes.onCreateViewHolder(AssignAdapterChooseBoxes.java:43)
        at com.plantecuador.poscosecha.adapter.AssignAdapterChooseBoxes.onCreateViewHolder(AssignAdapterChooseBoxes.java:32)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6949)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6001)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5997)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2227)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1558)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1518)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:613)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4032)
W/System.err:     at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3444)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at android.view.View.measure(View.java:19147)
        at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1236)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:650)
W/System.err:     at android.view.View.measure(View.java:19147)
        at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1723)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:788)
W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:648)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6113)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:223)
        at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2697)
        at android.view.View.measure(View.java:19147)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2486)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1450)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1704)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6713)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
        at android.view.Choreographer.doCallbacks(Choreographer.java:696)
        at android.view.Choreographer.doFrame(Choreographer.java:631)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
W/System.err:     at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
    Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
W/System.err:     at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:473)
    	... 88 more
```

**Comment by ronykrell** [comment]
Here is the listener
` 
```
holder.numberAssigned.setNumberPickerChangeListener(new NumberPicker.OnNumberPickerChangeListener() {
           @Override
           public void onProgressChanged(@NotNull NumberPicker numberPicker, int i, boolean b) {
               EventBus.getDefault().post(new BoxInsideAssignmentChangedEvent(inside,holder.numberAssigned.getProgress()));
           }

           @Override
           public void onStartTrackingTouch(@NotNull NumberPicker numberPicker) {

           }

           @Override
           public void onStopTrackingTouch(@NotNull NumberPicker numberPicker) {

           }
       });`
```

**Comment by dottjt** [comment]
I also get the same issue as well. I haven't figured out why.

**Comment by senpl** [comment]
My quick workaround with commenting UIGestures instead of Number from this repo use this in build.gradle :
`    implementation 'com.github.senpl:NumberSlidingPicker:2cd87266c8e7d7656df9eef964bf062da95833a3'
`
Until mantainer find time to fix issue.
