### ISSUE TITLE
On long press of up arrow or down arrow app crashes

### ISSUE THREAD

**Issue by prudhvi-rajkumar** [sephiroth74/NumberSlidingPicker#2]
On Long press of adjusters i.e, up arrow and down arrow the app is crashing. Here is the log report.

io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8261)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1348)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5433)
        at android.view.View.invalidateInternal(View.java:13982)
        at android.view.View.invalidate(View.java:13918)
        at android.widget.TextView.invalidateRegion(TextView.java:5946)
        at android.widget.TextView.invalidateCursor(TextView.java:5889)
        at android.widget.TextView.spanChange(TextView.java:9416)
        at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:12067)
        at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:1057)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:763)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:662)
        at android.text.Selection.setSelection(Selection.java:117)
        at android.text.Selection.setSelection(Selection.java:128)
        at android.text.method.ArrowKeyMovementMethod.initialize(ArrowKeyMovementMethod.java:325)
        at android.widget.TextView.setText(TextView.java:4976)
        at android.widget.TextView.setText(TextView.java:4834)
        at android.widget.EditText.setText(EditText.java:117)
        at android.widget.TextView.setText(TextView.java:4809)
        at it.sephiroth.android.library.numberpicker.NumberPicker.setProgress(NumberPicker.kt:118)
        at it.sephiroth.android.library.numberpicker.NumberPicker.setProgress$default(NumberPicker.kt:112)
        at it.sephiroth.android.library.numberpicker.NumberPicker$initializeButtonActions$1$1.accept(NumberPicker.kt:253)
        at it.sephiroth.android.library.numberpicker.NumberPicker$initializeButtonActions$1$1.accept(NumberPicker.kt:31)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58) 
        at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82) 
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532) 
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818)

**Comment by diegotmorais** [comment]
same here.
