### ISSUE TITLE
Entering long values throws error even max value is integer

### ISSUE THREAD

**Issue by nitheshbafna** [sephiroth74/NumberSlidingPicker#28]
2020-08-24 12:00:24.116 7419-7419/com.sree.eliteadvisor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sree.eliteadvisor, PID: 7419
    java.lang.NumberFormatException: For input string: "1888888888888888"
        at java.lang.Integer.parseInt(Integer.java:611)
        at java.lang.Integer.valueOf(Integer.java:794)
        at it.sephiroth.android.library.numberpicker.NumberPicker$initializeButtonActions$3.onFocusChange(NumberPicker.kt:350)
        at android.view.View.onFocusChanged(View.java:6921)

**Comment by ouedyan** [comment]
Yes. Same error with me.

**Comment by Sash0k** [comment]
duplicate for #10

**Comment by GuilhE** [comment]
fixed in #22

**Comment by MackHartley** [comment]
Can confirm this is an issue
